[general]
titulo = "Skell's ADO"
icono = "./img/icono.png"
logo = "./img/logo.png"
logotipo = "./img/logotipo.png"
wide = "centered"
sidebar_estado = "collapsed"

[desarrollo]
debug = false

[tablas]
usuarios = """
CREATE TABLE IF NOT EXISTS usuarios (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(20) NOT NULL,
    contrasena VARCHAR(20) NOT NULL,
    tipo INT NOT NULL,
    fechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (LENGTH(usuario) >= 4),
    CHECK (LENGTH(contrasena) >= 8)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
"""
clientes = """
CREATE TABLE IF NOT EXISTS clientes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    codigo_socio INT UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    correo VARCHAR(100),
    direccion VARCHAR(200),
    descripcion TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(1) DEFAULT 1,
    CONSTRAINT chk_cedula_length CHECK (CHAR_LENGTH(cedula) BETWEEN 6 AND 20),
    CONSTRAINT chk_nombre_length CHECK (CHAR_LENGTH(nombre) BETWEEN 2 AND 100),
    CONSTRAINT chk_telefono_length CHECK (CHAR_LENGTH(telefono) BETWEEN 7 AND 15),
    CONSTRAINT chk_codigo_socio_positive CHECK (codigo_socio IS NULL OR codigo_socio > 0),
    CONSTRAINT chk_email_format CHECK (correo IS NULL OR correo LIKE '%_@__%.__%')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
"""
productos = """
CREATE TABLE IF NOT EXISTS productos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL,
    cantidad INT NOT NULL DEFAULT 0,
    proveedor VARCHAR(100),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    estado TINYINT(1) DEFAULT 1,
    CONSTRAINT chk_codigo_length CHECK (CHAR_LENGTH(codigo) BETWEEN 1 AND 50),
    CONSTRAINT chk_nombre_length CHECK (CHAR_LENGTH(nombre) BETWEEN 2 AND 100),
    CONSTRAINT chk_precio_positive CHECK (precio >= 0),
    CONSTRAINT chk_cantidad_positive CHECK (cantidad >= 0),
    CONSTRAINT chk_proveedor_length CHECK (proveedor IS NULL OR CHAR_LENGTH(proveedor) BETWEEN 2 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
"""
ventas = """
CREATE TABLE IF NOT EXISTS ventas (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha_venta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Información del cliente
    id_cliente VARCHAR(20) NOT NULL,

    -- Información de productos
    id_producto INT NOT NULL,
    codigo_producto VARCHAR(50) NOT NULL,
    nombre_producto VARCHAR(100) NOT NULL,
    cantidad INT NOT NULL DEFAULT 1,
    precio_unitario DECIMAL(10, 2) NOT NULL,
    subtotal DECIMAL(12, 2) NOT NULL,

    -- Información de la transacción
    total DECIMAL(12, 2) NOT NULL,
    inicial DECIMAL(12, 2) NOT NULL DEFAULT 0,
    valor_cuota DECIMAL(12, 2) NOT NULL DEFAULT 0,
    metodo_pago VARCHAR(50) NOT NULL,
    estado_venta VARCHAR(20) DEFAULT 'completada' COMMENT 'completada, pendiente, cancelada',

    -- Información de cuotas
    cuotas INT NOT NULL DEFAULT 0,
    cuotas_pagadas INT NOT NULL DEFAULT 0,

    -- Información del vendedor
    vendedor VARCHAR(100) NOT NULL,

    -- Observaciones y metadata
    observaciones TEXT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(1) DEFAULT 1,

    -- Constraints de validación
    CONSTRAINT chk_total_positive CHECK (total >= 0),
    CONSTRAINT chk_inicial_positive CHECK (inicial >= 0),
    CONSTRAINT chk_valor_cuota_positive CHECK (valor_cuota >= 0),
    CONSTRAINT chk_subtotal_positive CHECK (subtotal >= 0),
    CONSTRAINT chk_precio_unitario_positive CHECK (precio_unitario >= 0),
    CONSTRAINT chk_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT chk_cuotas_positive CHECK (cuotas >= 0),
    CONSTRAINT chk_cuotas_pagadas_positive CHECK (cuotas_pagadas >= 0),
    CONSTRAINT chk_cuotas_pagadas_no_mayor CHECK (cuotas_pagadas <= cuotas),
    CONSTRAINT chk_metodo_pago_length CHECK (CHAR_LENGTH(metodo_pago) BETWEEN 2 AND 50),
    CONSTRAINT chk_estado_venta_valido CHECK (estado_venta IN ('completada', 'pendiente', 'cancelada')),
    CONSTRAINT chk_vendedor_length CHECK (CHAR_LENGTH(vendedor) BETWEEN 2 AND 100),
    CONSTRAINT chk_codigo_producto_length CHECK (CHAR_LENGTH(codigo_producto) BETWEEN 1 AND 50),
    CONSTRAINT chk_nombre_producto_length CHECK (CHAR_LENGTH(nombre_producto) BETWEEN 2 AND 100),

    -- Claves foráneas
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(cedula) 
        ON DELETE RESTRICT ON UPDATE CASCADE,
        
    CONSTRAINT fk_venta_producto FOREIGN KEY (id_producto) 
        REFERENCES productos(id) 
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""
chat = """
CREATE TABLE IF NOT EXISTS chat (
    id INT PRIMARY KEY AUTO_INCREMENT,
    usuario VARCHAR(100) NOT NULL,
    mensaje TEXT NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(1) DEFAULT 1,
    
    -- Constraints de validación
    CONSTRAINT chk_usuario_length CHECK (CHAR_LENGTH(usuario) BETWEEN 1 AND 100),
    CONSTRAINT chk_mensaje_length CHECK (CHAR_LENGTH(mensaje) BETWEEN 1 AND 5000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
"""